### ISSUE TITLE
Fails on language keywords

### ISSUE THREAD

**Issue by kassim** [SchibstedSpain/Protein#7] opened 2018-10-08 17:25 UTC
If you have a language keyword as one of your model names (e.g. `break`) it will fail, because its reserved.

**Comment by ferranpons** [comment] 2018-10-09 09:10
Hi @kassim,

If it's language reserved then it's the expected behavior because you would not be able to use that name because the IDE and compiler would complain about it anyway. You must change that name in order to be able to generate that code.
On the other side, if the plugin crashes after that maybe it should not crash and show a warning message about that.

**Comment by kassim** [comment] 2018-10-09 09:16
the way the https://github.com/swagger-api/swagger-codegen project works with Java code generation is it renames it to `ModelBreak`

**Comment by ferranpons** [comment] 2018-10-09 09:57
🤔 I'm not quite happy applying this criteria but if swagger-codegen is doing it I'll patch it with that.

**Comment by ferranpons** [comment] 2018-10-09 14:05
@kassim new version 1.0.1 have just been submitted to JetBrains. Includes the fix for this issue. Soon will be available for download.

I'll ping you as soon is available.

**Comment by ferranpons** [comment] 2018-10-09 15:06
@kassim New version 1.0.1 available for download. If you still have issues related to this please reopen the issue.

Many thanks for your help!

**Closed by ferranpons** 2018-10-09 15:06 UTC
